FROM datmo/dlib-scikit:14.04

# Run commands to make code work
RUN sudo apt-get update -y

# Numpy / Scipy reqs
RUN sudo apt-get install python-sympy -y
RUN pip install face_recognition
RUN pip install pandas
RUN pip install matplotlib

